### ISSUE TITLE
Removing the "fullscreen" button broke steam deck usability

### ISSUE THREAD

**Issue by jnackmclain** [Encore-Developers/Encore-Raylib#3]
When running via game mode, the title bar of the application is not visible, so you cannot maximize the window. Meaning the window is taking up only a portion of the already low resolution steam deck screen. Understandably, the ui does not properly scale this low, leading to the game being cumbersome to navigate and play in game mode.

**Comment by jnackmclain** [comment]
Sorry, should have mentioned this was tested on the latest action build. I reverted to release for now.

**Comment by NarrikSynthfox** [comment]
I'll add a resolution setting and full screen setting to the options menu and post again after that is done

**Comment by marie0llie** [comment]
thanks for reminding me about the fullscreen button! as of writing, im working on making a simple toggle in Settings to enable/disable fullscreen, alongside setting fullscreen to the default value

it'll most likely be fixed in the next commit. ill update u on that here

**Comment by marie0llie** [comment]
should be fixed in commit 1b425c2!

**Comment by jnackmclain** [comment]
This definitely helps and works, but figure I might as well report some issues with it.

When launching the game on steam deck, you will still get a small window taking up a small amount of the screen, this time with no title bar.
![image](https://github.com/Encore-Developers/Encore-Raylib/assets/55568980/26952b97-dfc4-4d25-adba-1743fc246b90)

Thankfully, you can navigate to options.
![image](https://github.com/Encore-Developers/Encore-Raylib/assets/55568980/6a4af2cb-cf10-41e1-8b6e-3e45f06449b8)

And simply pressing "apply" will actually make the game full screen.
![image](https://github.com/Encore-Developers/Encore-Raylib/assets/55568980/b03f65de-5865-451d-943e-d492af25a2e4)

**Comment by marie0llie** [comment]
I did notice this when I tested on my own Steam Deck recently, and it seems to partially resolve itself if you force a resolution in Game Mode, if launched from there. I'd have to research this more, but I'm currently away from home.

**Comment by jnackmclain** [comment]
No worries, no longer a dealbreaker anymore as I can work around it.
